//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Диплом
{
    using System;
    using System.Collections.Generic;
    
    public partial class Журнал_параметров
    {
        public int Код_записи { get; set; }
        public double Длина_камеры { get; set; }
        public double Длина_става { get; set; }
        public double Длина_пласта { get; set; }
        public Nullable<double> Количество_угля_с_одного_става { get; set; }
        public Nullable<double> Количество_единиц_угля_с_камеры { get; set; }
        public Nullable<double> Количество_ставов_на_камеру { get; set; }
        public Nullable<double> Количество_камер_в_пласте { get; set; }
    }
}
